name: CI

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: jorts.flatpak
          manifest-path: io.github.ellie_commons.jorts.yml
          run-tests: true
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
